name       : bdftopcf
version    : '1.1'
release    : 5
source     :
    - https://www.x.org/releases/individual/app/bdftopcf-1.1.tar.bz2 : 4b4df05fc53f1e98993638d6f7e178d95b31745c4568cee407e167491fd311a2
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: bdftopcf
description: |
    X.Org Applications: bdftopcf
builddeps  :
    - pkgconfig(xfont)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
