name       : bdftopcf
version    : 1.0.5
release    : 4
source     :
    - https://www.x.org/releases/individual/app/bdftopcf-1.0.5.tar.gz : 78a5ec945de1d33e6812167b1383554fda36e38576849e74a9039dc7364ff2c3
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: bdftopcf
description: |
    X.Org Applications: bdftopcf
builddeps  :
    - pkgconfig(xfont)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
